-- Sprint 11: The Technical Handover & Mission Control
-- Add blueprint storage and feature idea linkage to projects table

-- Add new columns to projects table
alter table projects
add column if not exists source_feature_idea_id uuid references feature_ideas(id) on delete set null,
add column if not exists ai_blueprint text;

-- Add index for efficient queries
create index if not exists idx_projects_source_feature_idea on projects(source_feature_idea_id);

-- Comments for clarity
comment on column projects.source_feature_idea_id is 'Links project to the original feature idea discussed during onboarding';
comment on column projects.ai_blueprint is 'Technical specification in Markdown generated by AI architect for developers';

-- Note: No need to add RLS policies - projects table already has RLS enabled with authenticated user policies
